server:
  address: 0.0.0.0
  port: 8765
spring:
  security:
    csrf:
      enabled: false
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: server1-route
          uri: ${SERVER1_ROUTE_URI:http://139.59.209.1:80}
          predicates:
            - Path=/api/**
          filters:
            - AddResponseHeader=X-Powered-By, DanSon Gateway Service
#            - AddResponseHeader = Access-Control-Allow-Origin: https://ocean-spray-rosy.vercel.app
        - id: server2-route
          uri: ${SERVER2_ROUTE_URI:http://167.71.253.191:5000}
          predicates:
            - Path=/server2/**
          filters:
            - AddResponseHeader=X-Powered-By, DanSon Gateway Service
#            - AddResponseHeader = Access-Control-Allow-Origin: https://ocean-spray-rosy.vercel.app
        - id: larvel-v2
          uri: ${SERVER2_ROUTE_URI:http://104.131.16.69:80}
          predicates:
            - Path=/api/analyze-map
          filters:
            - AddResponseHeader=X-Powered-By, DanSon Gateway Service
        #            - AddResponseHeader = Access-Control-Allow-Origin: https://ocean-spray-rosy.vercel.app

environment:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
